spring.application.name=MiniLink

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

minilink.base-url=${MINILINK_BASE_URL:http://localhost:8080/api/}